name: Scrape City Auslastung
on:
  schedule:
    - cron: "*/5 * * * *"  # every 5 minutes (UTC)
  workflow_dispatch: {}      # allow manual runs

permissions:
  contents: write            # allow committing the CSV

concurrency:
  group: scrape_city_csv
  cancel-in-progress: false

jobs:
  scrape:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Playwright (Python)
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          python -m playwright install --with-deps chromium

      - name: Run scraper
        run: python remote_scrape.py

      - name: Commit & push CSV
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add swiftbar_city_auslastung.csv
          git commit -m "Update CSV $(date -u +\"%Y-%m-%dT%H:%M:%SZ\")" || echo "No changes"
          git push
